### ISSUE TITLE
Link to master thesis on DWorlds is broken

### ISSUE THREAD

**Issue by LinqLover** [nikku/lefedt.de#2]
Hi @nikku, recently I could still access your master thesis through this link: http://nixis.de/~nikku/uni/master/thesis/exploring-run-time-behavior-nre-2012.pdf

Now it's unfortunately broken (404 Not Found) :(

Is it possible to publish this work again, as I was going to cite it? Unfortunately, I do not even have a local copy. If you do not want your thesis to be publicly available any longer, could you maybe send me a private copy via DM? (first.last@student.hpi.de)

This page still points to the broken link: https://lefedt.de/blog/posts/2012/master-thesis-finished/

**Comment by nikku** [comment]
@LinqLover I'll see if I can restore it, and fix the link in the process. Thanks!

What do you work on right now?

**Comment by LinqLover** [comment]
Thank you :-)

> What do you work on right now?

Right at the moment, Worlds and DWorlds are just a footnote for my research on an exploratory programming agent (https://github.com/LinqLover/SemanticSqueak). The agent uses GPT-4 for talking to Smalltalk objects in natural language, programmers ask conceptual questions and the agent executes Smalltalk code to answer the questions. It would be a useful safety net to capture the side effects of AI-generated do-its in a separate world until the programmer accepts them. Paper and master thesis are not yet published, let me know if you want more details :D

Besides that, your work is actually more relevant to a simple Sandbox (https://github.com/LinqLover/SimulationStudio#simulationstudio-sandbox) and a time-travel debugger (https://github.com/hpi-swa-lab/squeak-tracedebugger) (which also uses an isolation mechanism for queries over state changes) I worked on earlier. There is also some other ongoing research at @hpi-swa on exploring multiple versions of programs in parallel with Babylonian Programming examples. And Robert is dreaming of a generic undo mechanism for do-its in Squeak. So many exciting dots to connect. :-)

**Comment by nikku** [comment]
This is now restored. Thanks for sharing some background on your research. Very interesting.

**Comment by LinqLover** [comment]
Thanks! :-)
